### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by beicnet** [QuentinCG/Arduino-LM75A-Temperature-Sensor-Library#1]
Hi @QuentinCG 

Can you please make a simple plugin for ESPEasy too?

[https://github.com/letscontrolit/ESPEasyPluginPlayground](url)

Thank you!

Kind regards,
Viktor

**Comment by QuentinCG** [comment]
Hi @beicnet,

I don't know how this works.
If you want to help me on this, we could do it together.

Cheers,
Quentin

**Comment by beicnet** [comment]
Hi @QuentinCG 

How I see it's very simple, but my C language knowledge is limited, I'm in VB waters.

But, I can give you a simple I2C plugin example to see it how it works.

Kind regards,
Viktor

**Comment by QuentinCG** [comment]
Hi @beicnet,

Yep, please give me an I2C plugin example and an explanation on how to add this to the ESPEasyPluginPlayground project and I do it when I'll have some time ;)

Cheers,
Quentin

**Comment by beicnet** [comment]
Hey @QuentinCG 

It would be really nice from you! ;)

Here is the simple example for I2C DHT12 Sensor:
[https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P034_DHT12.ino](url)
I already started with development with your example code, I will post my results here.

It should look like this, already compiled without any errors, but I don't have the sensor yet, need to arrive tomorrow if I'm not wrong.

[https://github.com/beicnet/_P198_LM75A.ino/blob/master/_P198_LM75A.ino](url)

NOTE: Also we need to include your whole Library content into the Plugin (ino file) to reduce the compatibility issues and external library dependency.

Kind regards,
Viktor

**Comment by QuentinCG** [comment]
Hey @beicnet,

I looked at it and it seems good except the I2C address should be "configurable" to be usable by more people if the I2C address changes.

This should be in a define:

```
#define  LM75A_A0_PIN_SET false
#define  LM75A_A1_PIN_SET false
#define  LM75A_A2_PIN_SET false

(...)

LM75A lm75a_sensor(LM75A_A0_PIN_SET, LM75A_A1_PIN_SET, LM75A_A2_PIN_SET);
```
(a bit like done for the dynamic address in the example you gave me: https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P034_DHT12.ino)

Just to be sure: The temperature you get is in degrees (celcius). If you need degrees Fahrenheit, consider using ```getTemperatureInFahrenheit()``` function ;)


I keep this thread open until you tested your code with the real sensor, please tell me if it worked.

Cheers,
Quentin

**Comment by beicnet** [comment]
Hey @QuentinCG,

I got the sensors today, and guess what?! ;)

![lm75a_test_results](https://cloud.githubusercontent.com/assets/22061547/25177907/f4995a38-2503-11e7-9223-25a602165c48.png)

So, tell me, because I didn't read about it, what is for that SMD Led diode on the Sensor board?

And, another thing, how can I combine into the Plugin source the whole external LM75A library content?

Kind regards,
Viktor

**Comment by QuentinCG** [comment]
Hey @beicnet,


Nice!

I don't think I have a LED on my LM75A sensor but maybe in yours it is blinking when there is an I2C communication? (just guessing).

For your "how can I combine into the Plugin source the whole external LM75A library content" request, you can for example do this. I have to say it will work with less dependencies but it is "not a C++ pretty way to implement things" (you break the beauty of C++ by doing this =P).

Cheers,
Quentin

```
/////////////////////////// HUGLY WAY TO ADD LM75A CLASS WITHOUT HEADER ////////////////
#ifndef LM75A_h
#define LM75A_h

#include <Wire.h>

#if defined(ARDUINO) && ARDUINO >= 100
#include "Arduino.h"
#else
#include "WProgram.h"
#endif

#define INVALID_LM75A_TEMPERATURE 1000

namespace LM75AConstValues
{

const int LM75A_BASE_ADDRESS = 0x48;

const float LM75A_DEGREES_RESOLUTION = 0.125;

const int LM75A_REG_ADDR_TEMP = 0;
//const int LM75A_REG_ADDR_CONF = 1;  // Not used for now
//const int LM57A_REG_ADDR_THYST = 2; // Not used for now
//const int LM57A_REG_ADDR_TOS = 3;   // Not used for now

}

using namespace LM75AConstValues;

class LM75A
{
  public:
    LM75A(bool A0_value = false, bool A1_value = false, bool A2_value = false)
    {
        _i2c_device_address = LM75A_BASE_ADDRESS;

        if (A0_value) {
          _i2c_device_address += 1;
        }
      
        if (A1_value) {
          _i2c_device_address += 2;
        }
      
        if (A2_value) {
          _i2c_device_address += 4;
        }
      
        Wire.begin();
    }

    float getTemperatureInDegrees() const
    {
       uint16_t real_result = INVALID_LM75A_TEMPERATURE;
       uint16_t i2c_received = 0;

       // Go to temperature data register
       Wire.beginTransmission(_i2c_device_address);
       Wire.write(LM75A_REG_ADDR_TEMP);
       if(Wire.endTransmission()) {
         // Transmission error
         return real_result;
       }
      
       // Get content
       if (Wire.requestFrom(_i2c_device_address, 2)) {
         Wire.readBytes((uint8_t*)&i2c_received, 2);
       } else {
         // Can't read temperature
         return real_result;
       }
      
       // Modify the value (only 11 MSB are relevant if swapped)
       uint16_t refactored_value;
       uint8_t* ptr = (uint8_t*)&refactored_value;
      
       // Swap bytes
       *ptr = *((uint8_t*)&i2c_received + 1);
       *(ptr + 1) = *(uint8_t*)&i2c_received;
      
       // Shift data (left-aligned)
       refactored_value >>= 5;
      
       // Relocate negative bit (11th bit to 16th bit)
       if (refactored_value & 0x0400) {
         refactored_value &= 0x03FF;
         refactored_value |= 0x8000;
       }
      
       // Real value can be calculated with sensor resolution
       real_result = (float)refactored_value * LM75A_DEGREES_RESOLUTION;
      
      return (float)refactored_value * LM75A_DEGREES_RESOLUTION;
    }
    
  private:
    int _i2c_device_address;
};

#endif //LM75A_h

/////////////////////////////YOUR PLUGIN HERE////////////////////////
//#######################################################################################################
//######################## Plugin 198: Temperature Sensor LM75A (I2C) ###################################
//#######################################################################################################
//
// NOTE: requires the following library (LM75A):
//
// Library for Arduino by QuentinCG, 2016
// https://github.com/QuentinCG/Arduino-LM75A-Temperature-Sensor-Library
//
// Plugin for ESP Easy by: beicnet, 2017
// https://github.com/beicnet/_P198_LM75A.ino
//
//#######################################################################################################

#define PLUGIN_198
#define PLUGIN_ID_198         198
#define PLUGIN_NAME_198       "Temperature - LM75A (I2C)"
#define PLUGIN_VALUENAME1_198 "Temperature"

boolean Plugin_198_init = false;

// Default I2C address selected 0x48
#define LM75A_A0_PIN_SET false
#define LM75A_A1_PIN_SET false
#define LM75A_A2_PIN_SET false

boolean Plugin_198(byte function, struct EventStruct *event, String& string)
{
    boolean success = false;

    switch (function)
    {
        case PLUGIN_DEVICE_ADD:
        {
            Device[++deviceCount].Number = PLUGIN_ID_198;
            Device[deviceCount].Type = DEVICE_TYPE_I2C;
            Device[deviceCount].VType = SENSOR_TYPE_SINGLE;
            Device[deviceCount].Ports = 0;
            Device[deviceCount].PullUpOption = false;
            Device[deviceCount].InverseLogicOption = false;
            Device[deviceCount].FormulaOption = true;
            Device[deviceCount].ValueCount = 1;
            Device[deviceCount].SendDataOption = true;
            Device[deviceCount].TimerOption = true;
            Device[deviceCount].GlobalSyncOption = true;
            break;
        }

        case PLUGIN_GET_DEVICENAME:
        {
            string = F(PLUGIN_NAME_198);
            break;
        }

        case PLUGIN_GET_DEVICEVALUENAMES:
        {
            strcpy_P(ExtraTaskSettings.TaskDeviceValueNames[0], PSTR(PLUGIN_VALUENAME1_198));
            break;
        }

        case PLUGIN_READ:
        {

            LM75A lm75a_sensor(LM75A_A0_PIN_SET,  //A0 LM75A pin state
             LM75A_A1_PIN_SET,  //A1 LM75A pin state
             LM75A_A2_PIN_SET); //A2 LM75A pin state

            float tempC = lm75a_sensor.getTemperatureInDegrees();

            if (tempC == INVALID_LM75A_TEMPERATURE) {
                String log = F("LM75A: No reading!");
                addLog(LOG_LEVEL_INFO, log);
                UserVar[event->BaseVarIndex] = NAN;
                } else {
                UserVar[event->BaseVarIndex] = tempC;
                String log = F("LM75A: Temperature: ");
                log += UserVar[event->BaseVarIndex];
                addLog(LOG_LEVEL_INFO, log);
                success = true;
            }
            break;
        }
    }
    return success;
}
```

**Comment by beicnet** [comment]
Hey @QuentinCG,

Thank you for all! ;)

How I read, the OS pin has a multiple functionality, but what I understand from it, it's a Thermal watchdog for over temperature?!

Kind regards,
Viktor

**Comment by QuentinCG** [comment]
Hey,

The OS pin is indeed an output at 0 if no over temperature and 1 if over temperature is reached (with a system of interrupt or comparator mode, note that it could be the opposite depending on your configuration: 1 for "no over temperature" and 0 for "over temperature")... This is maybe not clear and this schema will be more explicit:
![os_lm75a](https://cloud.githubusercontent.com/assets/16922101/25234141/7ea14eba-25e1-11e7-8b26-f457ea378f9e.png)

To use this functionality, you need to configure the Tos and the mode with I2C (not done in this arduino library since I didn't need it).

Do you need this functionality? If yes, maybe we could work together on this.

Cheers,
Quentin

Source:
Picture: [http://www.tij.co.jp/ods/images/SNOS808P/1265807.png](http://www.tij.co.jp/ods/images/SNOS808P/1265807.png)
Datasheet: [http://www.ti.com/lit/ds/symlink/lm75a.pdf](http://www.ti.com/lit/ds/symlink/lm75a.pdf)

**Comment by beicnet** [comment]
Hey @QuentinCG,

Yeah, I figured that out, so basically that LED diode will go ON and OFF on those over temperature state, right?!

Regarding that additional functionality, it's not needed, because the current system has an built in Rules and you can do anything you wish with any device/sensor attached to it.

I have another proposal/project for you if you are interested, as I mentioned, I'm not in the C language, so I need a lot of help.

Kind regards,
Viktor

btw...Did you see my finished Github regarding LM75A? I made "C" pretty as I can! ;)

**Comment by QuentinCG** [comment]
Hey @beicnet,

> Yeah, I figured that out, so basically that LED diode will go ON and OFF on those over temperature state, right?!

Yep, it seems so (even if I didn't find any information about this LED...)


> I have another proposal/project for you if you are interested, as I mentioned, I'm not in the C language, so I need a lot of help.

Why not ;) (I don't have unlimited time thought...)


> btw...Did you see my finished Github regarding LM75A? I made "C" pretty as I can! ;)

I saw your work and it seems pretty good for me. Thanks for the "credit" by the way.


Cheers,
Quentin
