### ISSUE TITLE
Wrong negative Celisius values

### ISSUE THREAD

**Issue by andrzejboro** [QuentinCG/Arduino-LM75A-Temperature-Sensor-Library#2]
Hi, there's a problem with readings of negative Celsius values. I already have a fix, but since I'm new to github community, I can't push it.
Please, let me know how to do it.

**Comment by QuentinCG** [comment]
Hi,

Thanks for your help!

You can either:
 - Put you source code by dragging your source code here and I'll do the fix myself
 - Do a pull request (most common way to do): You fork my repo, you do your fix and then create a pull request on my repo ( more information here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by QuentinCG** [comment]
Thanks.
Your fix is merged in the repository. I added you as a "contributor" in the README.

Note for your next pull request: You did a pull request in your repository and not in mine.
Next time, try to do in the right repository else the users will not see the request.
