### ISSUE TITLE
Set address

### ISSUE THREAD

**Issue by foscone** [QuentinCG/Arduino-LM75A-Temperature-Sensor-Library#4]
Hi, how can I set the lm75a address to 0x48?
Thanks!

**Comment by QuentinCG** [comment]
I2C address span is 0x48 - 0x4F, and is set with pins A0/A1/A2.

Therefore you need to have A0,A1 and A2 to 0v and initialize the library like this:
`LM75A(A0_value = false, A1_value = false, A2_value = false);`
